### ISSUE TITLE
Postgreslet: Add "slow queries" query to metrics exporter

### ISSUE THREAD

**Issue by eberlep** [metal-stack/helm-charts#35]
In the values file, add the following query to `sidecars.exporter.queries`:

```yaml
  pg_stat_statements:
  query: "SELECT
             pg_get_userbyid(userid) as user,
             pg_database.datname,
             pg_stat_statements.queryid,
             pg_stat_statements.query,
             pg_stat_statements.calls,
             pg_stat_statements.total_exec_time as time_milliseconds,
             pg_stat_statements.rows,
             pg_stat_statements.shared_blks_hit,
             pg_stat_statements.shared_blks_read,
             pg_stat_statements.shared_blks_dirtied,
             pg_stat_statements.shared_blks_written,
             pg_stat_statements.local_blks_hit,
             pg_stat_statements.local_blks_read,
             pg_stat_statements.local_blks_dirtied,
             pg_stat_statements.local_blks_written,
             pg_stat_statements.temp_blks_read,
             pg_stat_statements.temp_blks_written,
             pg_stat_statements.blk_read_time,
             pg_stat_statements.blk_write_time
          FROM pg_stat_statements
          JOIN pg_database
          ON pg_database.oid = pg_stat_statements.dbid"
  metrics:
    - user:
        usage: "LABEL"
        description: "The user who executed the statement"
    - datname:
        usage: "LABEL"
        description: "The database in which the statement was executed"
    - queryid:
        usage: "LABEL"
        description: "Internal hash code, computed from the statement's parse tree"
    - query:
        usage: "LABEL"
        description: "Processed query"
    - calls:
        usage: "COUNTER"
        description: "Number of times executed"
    - time_milliseconds:
        usage: "COUNTER"
        description: "Total time spent in the statement, in milliseconds"
    - rows:
        usage: "COUNTER"
        description: "Total number of rows retrieved or affected by the statement"
    - shared_blks_hit:
        usage: "COUNTER"
        description: "Total number of shared block cache hits by the statement"
    - shared_blks_read:
        usage: "COUNTER"
        description: "Total number of shared blocks read by the statement"
    - shared_blks_dirtied:
        usage: "COUNTER"
        description: "Total number of shared blocks dirtied by the statement"
    - shared_blks_written:
        usage: "COUNTER"
        description: "Total number of shared blocks written by the statement"
    - local_blks_hit:
        usage: "COUNTER"
        description: "Total number of local block cache hits by the statement"
```

via https://gist.github.com/adivinho/756ebb95ddefa74b085ad51347b17ebc / https://www.percona.com/blog/2019/04/23/adding-postgresql-queries-overview-dashboards-to-the-pmm-plugin/
