### ISSUE TITLE
Expose filesystem parameter

### ISSUE THREAD

**Issue by neodino** [metal-stack/helm-charts#77]
Enable configurable filesystem parameter on storage classes in values.yaml.

i.e:
```
...
storageClasses:
  linear:
    fsType: xfs
  striped:
    fsType: xfs
  mirror:
    fsType: xfs
```
